version: "3.7"

services:
  database:
    image: postgres
    container_name: crud-rest-api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crud-rest-api
    volumes:
      - pg_data:/data/postgres

volumes:
  pg_data:
    driver: local
